config/routes.rb
Rails.application.routes.draw do

    root 'sessions#welcome'

    get '/signup', to: 'users#new'
    post '/signup', to: 'users#create'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'

    #OAuth Routes
    get '/auth/:provider/callback', to: 'sessions#omniauth'

    #Scope Routes
    post "playlist", to: "playlist#playlist_filter", as: "playlist_filter"

    resources :users, only: [:show]
    resources :playlists, only: [:index, :new, :create, :show, :edit, :destroy]

    resources :users do
        resources :playlists, shallow: true
    end

    

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :playlist
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    has_many :playlist_tracks, dependent: :destroy
    has_many :tracks, through: :playlist_tracks
    has_many :comments
    belongs_to :user

    #add validations for presence of name and user_id

    #scope - alphabetize, current length of playlist?, 
    scope :public_playlists, -> { where( public: true )}
end

app/models/playlist_track.rb
class PlaylistTrack < ApplicationRecord
    belongs_to :track
    belongs_to :playlist
    belongs_to :user
end

app/models/track.rb
class Track < ApplicationRecord
    has_many :playlist_tracks
    has_many :playlists, through: :playlist_tracks       
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :playlist_tracks
    has_many :playlists #as: owner?
    # has_many :playlists, through: :playlist_tracks
    has_many :comments

    validates :email, presence: true
    validates :email, uniqueness: true

    
    def self.create_by_github_omniauth(auth)
      self.find_or_create_by(email: auth[:info][:email]) do |u|
        u.first_name = auth[:info][:name].split[0]
        u.last_name = auth[:info][:name].split[1]
        u.password = SecureRandom.hex 
      end
    end
    

    # def self.create_by_google_omniauth(auth)
    #   self.find_or_create_by(username: auth[:info][:email]) do |u|
    #     u.password = SecureRandom.hex
    #   end
    # end
  
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private

    def logged_in?
       !!session[:user_id] 
    end

    def current_user
       @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id] 
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in?
    end
    
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

    before_action :redirect_if_not_logged_in
    # add this functionality for authorization
    before_action :set_playlist, only: [:show, :edit, :update]
    before_action :redirect_if_not_playlist_user, only: [:edit, :update] #should I add index, as well?


    def index
        if params[:user_id] && params[:user_id].to_i == current_user.id
            #direct authorization call
            @user = User.find_by_id(params[:user_id])
            @playlists = @user.playlists.uniq
        else
            @playlists = Playlist.all
        end
	end

    def new
        @playlist = Playlist.new
        @playlist.user_id = current_user.id
	end

    def create
        playlist = Playlist.new(playlist_params)
        # playlist.user_id = current_user.id
        playlist.save
        redirect_to playlists_path(playlist)
	end

    def show
        # @playlist = Playlist.find_by_id(params[:id])
        # #is this next line necessary?
        @playlist_tracks = PlaylistTrack.where(user_id: current_user.id, playlist_id: @playlist.id)
        # if !@playlist
        #     flash[:error] = "Playlist not found."
        #     redirect_to playlists_path
        # end          
	end

    def edit
        # @playlist = Playlist.find_by_id(params[:id])
    end

    def update
        # @playlist = Playlist.find_by_id(params[:id])
        if @playlist.update(playlist_params)
            redirect_to playlist_path(@playlist)   
        else
            render :edit 
        end   
    end

    def destroy
        Playlist.find(params[:id]).destroy
        redirect_to playlists_path
    end

    def playlist_filter #add route
        binding.pry
        if params[:playlist][:public]
            @playlists = Playlist.public_playlists
        end

    end
    
    private

    def playlist_params
       params.require(:playlist).permit(:name, :description, :user_id, :public)
    end

    def set_playlist
        @playlist = Playlist.find_by_id(params[:id])
        if !@playlist
            flash[:error] = "Playlist not found"
            redirect_to playlists_path
        end
    end

    #must have set_playlist method to work?
    def redirect_if_not_playlist_user #switch to owner
        if params[:user_id].to_i != current_user.id
            flash[:error] = "Not authorized to access"
            redirect_to playlists_path #do I need?  Causing infinite loop
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

   
    def welcome
        
    end

    def destroy
       session.clear
       redirect_to root_path
    end

    def new 
        @user = User.new
    end

    def create
        #check for omniauth providers here.  If none, then do this:
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:error] = "Login Failed.  Please try again."
            redirect_to login_path           
        end
    end

    def omniauth
        @user = User.create_by_github_omniauth(auth)
         #so there's a first name!  Maybe I should have a username?
        session[:user_id] = @user.id
        redirect_to user_path(@user)
    end     

    private

    def auth
        request.env['omniauth.auth']
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def new

    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:error] = "Account creation failed:  #{@user.errors.full_messages.to_sentence}."
            render :new
        end      
    end

    def show
        @user = User.find_by_id(params[:id])
    end

    # def show
    #     redirect_if_not_logged_in
    #     @user = User.find_by_id(params[:id])
    #     redirect_to '/' if !@user
    # end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommunityPlaylister</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
   <!-- <link href="starter-template.css" rel="stylesheet"> already included by application.css -->
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">Commmunity Playlisters</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if current_user %>
        <li class="nav-item">
            <a class="nav-link" href="/users/<%= current_user.id %>">My Library</a>
        </li>
        <!-- change to User's Playlists - right now it's linked to All Playlists -->
        <li class="nav-item">
            <a class="nav-link" href="/users/<%= current_user.id %>/playlists">My Playlists</a> 
        </li>
      <% end %>
    
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Playlists</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Public Playlists</a>
          <a class="dropdown-item" href="#">My Playlists</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
          <% if !current_user%>
            <li class="nav-item">
              <a class="nav-link" href="/signup">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <% else %>
            <li class="nav-item">
           <!--  <%= link_to "Log Out", logout_path, method: :delete %>-->
            <a class="nav-link" rel="nofollow" data-method="delete" href="/logout">Logout</a>
             <!-- <a class="nav-link" href="/logout" method="DELETE">Logout</a> -->
            </li>
          <% end %>
        </ul>
    <!--
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>-->
  </div>
</nav>
<main role="main" class="container">

  <div class="starter-template">
   <!-- <h1>Bootstrap starter template</h1>
    <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>>-->

     <!-- Added ERB for Flash notices -->
        <!-- <%= "<div class='notice'>#{flash[:notice]}</div>" if flash[:notice]  %> -->
    <% if flash[:error] %>
      <h5 style="color:red;"><%= flash[:error] %></h5>
    <% end %>

    <% if flash[:message] %>
      <h5 style="color:green;"><%= flash[:message] %></h5>
    <% end %>

       <%= yield %>
  </div>
 
</main><!-- /.container -->
  
  

    <!-- Bootstrap JQuery, Popper, and JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  </body>
</html>

app/views/playlists/edit.html.erb
<h1>Edit <%= @playlist.name %></h1>
<br>

<div class="row justify-content-center">
        <%= bootstrap_form_for(@playlist) do |f| %>

                <%= f.form_group :public do %>
                    <%= f.check_box :public, label: "Make Public" %>
                <% end %>
            
                <%= f.text_field :name %>
                <br>
                <%= f.text_area :description %>
            
          
            <div class="text-center">
                <%= f.submit "Update Playlist", class: "btn btn-primary" %>
            </div>
        <% end %>
</div>

app/views/playlists/index.html.erb
<h1>Playlists#index</h1>
<br>
<%= link_to "Add New Playlist", new_playlist_path %>
<br>

  
    <table class="table table-striped text-left">
        <thead>
            <tr>
            <th scope="col">Playlist Name</th>
            <th scope="col">Description</th>
            <!--<th scope="col">Description</th>-->
            </tr>
        </thead>
        <tbody>
            <% @playlists.each do |playlist| %>
                <tr>
                    <td><%= link_to "#{playlist.name}", playlist_path(playlist) %></td>
                    <td><%= playlist.description %></td>
                </tr>
            <% end %>
        </tbody>
    </table>


 
</div>

app/views/playlists/new.html.erb
<h1>Add a New Playlist</h1>

<div class="row justify-content-center">
        <%= bootstrap_form_for(@playlist) do |f| %>
                <%= f.hidden_field :user_id  %>

                <%= f.form_group :public do %>
                    <%= f.check_box :public, label: "Make Public" %>
                <% end %>

                <%= f.text_field :name %>
                <br>
                <%= f.text_area :description %>
            
          
            <div class="text-center">
                <%= f.submit "Add New Playlist", class: "btn btn-primary" %>
            </div>
        <% end %>
</div>

app/views/playlists/show.html.erb
<h1><%= @playlist.name %></h1>
<h3><%= @playlist.description %></h3>

<%= link_to "Delete Playlist", playlist_path(@playlist), method: :delete, data: { confirm: "Are you sure you want to delete this playlist?" } %>

<table class="table table-striped text-left">
        <thead>
            <tr>
            <th scope="col">Name</th>
            <th scope="col">Artist</th>
            <th scope="col">Album</th>
            <th scope="col">Duration</th>
            <th scope="col">Sound Sample</th>
            <!--<th scope="col">Description</th>-->
            </tr>
        </thead>
        <tbody>
            <% @playlist_tracks.each do |playlist_track| %>
                <tr>
                    <td><%= playlist_track.track.name %></td>
                    <td>Artist</td>
                    <td>Album</td>
                    <td>Duration</td>
                    <td>Sound Sample</td>    
                </tr>
            <% end %>
        </tbody>
    </table>

app/views/users/new.html.erb

<div class="container p-3 my-3 bg-light">
    <h3 class="text-center">Sign Up to Community Playlisters!</h3>
    <br>

    <div class="row justify-content-center">
        <%= bootstrap_form_for :user do |f| %>
            <div class="form-row">
                <%= f.text_field :first_name %>
                <%= f.text_field :last_name %>
            </div>

            <%= f.email_field :email %>
            <%= f.password_field :password %>

            <div class="text-center">
                <%= f.submit "Sign Up", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb


<h2>Show page for <%= @user.first_name %></h2>

<%= link_to 'Add New Playlist', new_user_playlist_path(@user) %>